// Code generated by FTL. DO NOT EDIT.
package recommendation

import (
	"context"
	ftlbuiltin "ftl/builtin"
	ftlproductcatalog "ftl/productcatalog"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
	"github.com/block/ftl/go-runtime/server"
)

type ListClient func(context.Context, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, ListRequest]) (ftlbuiltin.HttpResponse[ListResponse, ErrorResponse], error)

func init() {
	reflection.Register(

		reflection.ProvideResourcesForVerb(
			List,
			server.VerbClient[ftlproductcatalog.ListClient, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, ftlproductcatalog.ListRequest], ftlbuiltin.HttpResponse[ftlproductcatalog.ListResponse, ftl.Unit]](),
		),
	)
}
