// Code generated by FTL. DO NOT EDIT.
package payment

import (
	"context"
	ftlbuiltin "ftl/builtin"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
)

type ChargeClient func(context.Context, ftlbuiltin.HttpRequest[ChargeRequest, ftl.Unit, ftl.Unit]) (ftlbuiltin.HttpResponse[ChargeResponse, ErrorResponse], error)

func init() {
	reflection.Register(

		reflection.ProvideResourcesForVerb(
			Charge,
		),
	)
}
