// Code generated by FTL. DO NOT EDIT.
package ad

import (
	"context"
	ftlbuiltin "ftl/builtin"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
)

type GetClient func(context.Context, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, AdRequest]) (ftlbuiltin.HttpResponse[AdResponse, ftl.Unit], error)

func init() {
	reflection.Register(

		reflection.ProvideResourcesForVerb(
			Get,
		),
	)
}
