// Code generated by FTL. DO NOT EDIT.
package cart

import (
	"context"
	ftlbuiltin "ftl/builtin"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
)

type AddItemClient func(context.Context, ftlbuiltin.HttpRequest[AddItemRequest, ftl.Unit, ftl.Unit]) (ftlbuiltin.HttpResponse[AddItemResponse, ftl.Unit], error)

type EmptyCartClient func(context.Context, ftlbuiltin.HttpRequest[EmptyCartRequest, ftl.Unit, ftl.Unit]) (ftlbuiltin.HttpResponse[EmptyCartResponse, ftl.Unit], error)

type GetCartClient func(context.Context, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, GetCartRequest]) (ftlbuiltin.HttpResponse[Cart, ftl.Unit], error)

func init() {
	reflection.Register(
		reflection.ProvideResourcesForVerb(
			AddItem,
		),
		reflection.ProvideResourcesForVerb(
			EmptyCart,
		),
		reflection.ProvideResourcesForVerb(
			GetCart,
		),
	)
}
