// Code generated by FTL. DO NOT EDIT.
package currency

import (
	"context"
	ftlbuiltin "ftl/builtin"
	"github.com/block/ftl/common/reflection"
	"github.com/block/ftl/go-runtime/ftl"
)

type ConvertClient func(context.Context, ftlbuiltin.HttpRequest[ConvertRequest, ftl.Unit, ftl.Unit]) (ftlbuiltin.HttpResponse[Money, string], error)

type GetSupportedCurrenciesClient func(context.Context, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, ftl.Unit]) (ftlbuiltin.HttpResponse[GetSupportedCurrenciesResponse, ftl.Unit], error)

func init() {
	reflection.Register(

		reflection.ProvideResourcesForVerb(
			Convert,
		),

		reflection.ProvideResourcesForVerb(
			GetSupportedCurrencies,
		),
	)
}
